### ISSUE TITLE
Make error

### ISSUE THREAD

**Issue by fox2402** [mycroft/nsc#1]
I used ./configure, then make returns this : 
make  all-am
make[1]: Entering directory '/home/poi/nsc'
if gcc -DHAVE_CONFIG_H -I. -I. -I.   -DNETWORK_DEBUG -D_GNU_SOURCE -g -O2 -MT nsc_main.o -MD -MP -MF ".deps/nsc_main.Tpo" \
  -c -o nsc_main.o `test -f 'nsc_main.c' || echo './'`nsc_main.c; \
then mv -f ".deps/nsc_main.Tpo" ".deps/nsc_main.Po"; \
else rm -f ".deps/nsc_main.Tpo"; exit 1; \
fi
Makefile:336: recipe for target 'nsc_main.o' failed
make[1]: Leaving directory '/home/poi/nsc'
Makefile:208: recipe for target 'all' failed

Hope it can help or maybe i did something wrong.

**Comment by mycroft** [comment]
Hi, nsc is quite old and I'm not sure it still useful. However, is is possible to know what is your environment ? system/distro - make -v; gcc -v; do you have any autotool installed ?

FYI I just compiled it successfully on Fedora 23

**Comment by mycroft** [comment]
I was able to reproduce the problem on a debian system where libreadline headers were missing.
Please install libreadline6-dev if you're on debian to fix it. If impossible, I think it will be required to patch source code.

**Comment by D0tty** [comment]
Great it fixed it for me :+1: 
I think I didn't install the good lib ^^
Thanks

**Comment by fox2402** [comment]
(10 thousand years later): yep it works, thanks a lot :dancer:
